Updating resources section on Homepage
fluxcd/website pull request #1046
Opened 2022-07-18 17:47 UTC by Santosh1176

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

Updates the resources section on the homepage with updated YouTube resources.
This PR would resolve issue [#941](https://github.com/fluxcd/website/issues/941#issue-1236770970)

2022-07-19 08:45 UTC, dholbach commented
https://deploy-preview-1046--fluxcd.netlify.app/ looks great to me.

@staceypotter What do you think?

2022-07-20 17:07 UTC, staceypotter requested changes
Made some suggestions for the descriptions on some of these. Thanks so much for this @Santosh1176 and great job!

2022-07-20 17:07 UTC, staceypotter commented on content/en/_index.html
> +  A playlist with a compilation of all talks during GitOps Days 2022 on June 8-9, 2022.
WDYT about this instead:
Playlist from GitOps Days 2022 on June 8-9, 2022 featuring Flux integrators, end-users/adopters, and maintainers.

2022-07-23 11:48 UTC, Santosh1176 commented
@staceypotter Thanks for the suggestions, I've updated the description accordingly.

2022-07-25 08:46 UTC, dholbach approved these changes
Thanks a lot @Santosh1176

2022-07-25 08:46 UTC, merged