add september blog post
fluxcd/website pull request #1176
Opened 2022-10-04 16:00 UTC by dholbach

Signed-off-by: Daniel Holbach <daniel@weave.works>

2022-10-04 16:04 UTC, dholbach commented
I wasn't sure what to use as "featured image" in https://deploy-preview-1176--fluxcd.netlify.app/blog/ - if anyone has suggestions, let me know.

2022-10-04 16:10 UTC, makkes commented
> I wasn't sure what to use as "featured image" in https://deploy-preview-1176--fluxcd.netlify.app/blog/ - if anyone has suggestions, let me know.

Maybe an icon comprised of the [OCI logo](https://github.com/opencontainers) and the Flux logo?

Or a sunset (as a symbol for the Flux v1 retirement).

2022-10-04 17:18 UTC, dholbach commented
Are we generally good with the legacy part?

2022-10-04 18:48 UTC, aryan9600 requested changes

2022-10-04 18:48 UTC, aryan9600 commented on content/en/blog/2022-10-04-september-update/index.md
> +> Paulo Gomes & Sanskar Jaiswal (Weaveworks)
```suggestion
> Somtochi Onyekwere & Kingdon Barrett (Weaveworks)
```

2022-10-04 18:48 UTC, aryan9600 commented on content/en/blog/2022-10-04-september-update/index.md
> +
```suggestion

11:40 - 12:10 Promethus Days: [Automate your SLO validation with Prometheus & Flagger](https://sched.co/1AsMU)

> Sanskar Jaiswal & Kingdon Barrett (Weaveworks)

```

2022-10-04 20:31 UTC, scottrigby commented
this is looking good btw!

2022-10-05 06:14 UTC, dholbach commented
I added a flux+oci logo - if somebody wants to improve it - please go ahead :-D

2022-10-05 08:03 UTC, phillebaba approved these changes
LGTM!

2022-10-05 09:19 UTC, makkes commented
The feature image is too heavily cropped in my view:
![2022-10-05_11-14_1](https://user-images.githubusercontent.com/387444/194025792-fd3218cc-b8a5-487b-bc58-4b87e63b26b3.png)

I changed it a little so that not as much content is cropped off of it:

![2022-10-05_11-14](https://user-images.githubusercontent.com/387444/194025893-9455f58a-6ffb-44ff-9058-1b23be3c32ff.png)

I can't directly contribute to this PR as it comes from a fork but here's a commit changing the feature image: https://github.com/fluxcd/website/blob/ab9bb9312960279cfedd600e9ea726cce9664693/content/en/blog/2022-10-04-september-update/flux%2Boci-featured.png

2022-10-05 09:27 UTC, dholbach commented
Thanks a lot @makkes!

2022-10-05 09:31 UTC, dholbach commented
This looks better now!

2022-10-05 09:52 UTC, merged