add KubeCon 2022 NA blog post
fluxcd/website pull request #1213
Opened 2022-10-19 15:56 UTC by dholbach

Signed-off-by: Daniel Holbach <daniel@weave.works>

2022-10-19 15:58 UTC, dholbach commented
→ https://deploy-preview-1213--fluxcd.netlify.app/blog/

2022-10-19 20:11 UTC, staceypotter requested changes
Just one schedule change I noticed, thanks for putting this together @dholbach! 🙇‍♀️

2022-10-19 20:11 UTC, staceypotter commented on content/en/blog/2022-10-19-kubecon-2022-na/index.md
> +16:55 - 17:30 KubeCon: [Flux Maturity, Feature, and Contrib
This talk was moved to Thursday, October 27 from 14:30 - 15:05

2022-10-20 08:23 UTC, stefanprodan approved these changes

2022-10-20 08:52 UTC, merged