Add November wrap-up blog post
fluxcd/website pull request #1291
Opened 2022-11-30 15:36 UTC by dholbach

Still WIP, let's aim for 2022-12-05.

Signed-off-by: Daniel Holbach <daniel@weave.works>

2022-11-30 15:39 UTC, dholbach commented
→ https://deploy-preview-1291--fluxcd.netlify.app/blog

2022-11-30 15:40 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
@jamwils If you, or anyone in your team, could help out with this section, that'd be great!

2022-11-30 15:41 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
@kingdonb Anything we should change here apart from the links and times? AND of course mention the special occasion!

2022-11-30 15:43 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
@juozasg Anything you'd like us to mention here?

2022-12-05 11:43 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
Ping. If possible, I would like to release this update today.

2022-12-05 11:43 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
Ping. If possible, I would like to release this update today.

2022-12-05 11:43 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
Ping. If possible, I would like to release this update today.

2022-12-05 13:07 UTC, dholbach commented on content/en/blog/2022-12-01-november-update/index.md
> +
https://www.youtube.com/watch?v=uRiCRTSkPOQ for example, right?

2022-12-05 14:29 UTC, staceypotter commented on content/en/blog/2022-12-01-november-update/index.md
> +- [Nov 29: WOUG: OCI - Flux ease with helm charts and Flux (Part
Nov 29 event should be moved to "recent" instead of "upcoming"

2022-12-05 14:29 UTC, staceypotter commented on content/en/blog/2022-12-01-november-update/index.md
> +- [Nov 30: HashiCorp User Group (Luxembourg): GitOps Your Terraform
Nov 30 event should be moved to "recent" instead of "upcoming"

2022-12-05 16:12 UTC, sympatheticmoose commented
Suggested text for Weave GitOps in the ecosystem section:

Weave GitOps
GitOps Run continues to be enhanced as an easy way to get started with Flux and GitOps, and now includes yaml validation for both Flux and core Kubernetes resources. The Weave GitOps UI for Flux is now able to support multiple instances of Flux on the same cluster, for when resource isolation strategies are in place, so you can see the health of all controllers in the Flux Runtime view. Then in the Enterprise edition of Weave GitOps, the Pipelines feature is now enabled by default to help you automatically promote applications through a series of environments, and GitOpsTemplates continue to be enhanced as a generic self-service capability for building out an Internal Developer Platform.

2022-12-05 17:02 UTC, aryan9600 requested changes

2022-12-05 17:02 UTC, aryan9600 commented on content/en/blog/2022-12-01-november-update/index.md
> +session affinity for Istio. Furthermore, it contains a regression fix
```suggestion
session affinity for Istio. Check out the tutorial [here](https://fluxcd.io/flagger/tutorials/istio-progressive-delivery/#session-affinity) Furthermore, it contains a regression fix
```

2022-12-05 17:02 UTC, aryan9600 commented on content/en/blog/2022-12-01-november-update/index.md
> +tutorial](https://docs.flagger.app/tutorials/gatewayapi-progressive-delivery).
```suggestion
tutorial](https://fluxcd.io/flagger/tutorials/gatewayapi-progressive-delivery/).
```
lets start using `fluxcd.io/flagger` from now on?

2022-12-05 17:12 UTC, aryan9600 approved these changes
lgtm, just one small nit

2022-12-05 17:12 UTC, aryan9600 commented on content/en/blog/2022-12-01-november-update/index.md
> +session affinity for Istio. Check out the tutorial [here](https://fluxcd.io/flagger/tutorials/istio-progressive-delivery/#session-affinity) Furthermore, it contains a regression fix
```suggestion
session affinity for Istio. Check out the tutorial [here](https://fluxcd.io/flagger/tutorials/istio-progressive-delivery/#session-affinity). Furthermore, it contains a regression fix
```

2022-12-05 17:18 UTC, merged