don't use legacy slack config in example
fluxcd/website pull request #1351
Opened 2023-01-05 20:51 UTC by digitalbanana

Signed-off-by: Dave Lowe <dave@digitalbanana.co.uk>

proposed change to use the recommended slack integration (not legacy)

2023-01-05 22:36 UTC, kingdonb commented
Thanks, can you squash your commits @digitalbanana 

I think I noticed this issue when I was setting up notifications last time (the legacy webhook is no longer an option to create, so you have to use the Bot token, but nothing else changes in these instructions),

Thank you for making a PR to close it 🎉

2023-01-05 22:37 UTC, kingdonb commented
It looks like you have noticed some things I didn't spot myself, actually

Please squash and let me know when you are finished, then we can approve it 👍

2023-01-05 22:38 UTC, kingdonb requested changes
Squash please

2025-01-03 12:32 UTC, digitalbanana commented
obsolete - didnt get round to this :-(

2025-01-03 12:32 UTC, closed without merging