May Update 2023
fluxcd/website pull request #1513
Opened 2023-06-02 17:06 UTC by somtochiama

2023-06-03 05:44 UTC, dholbach commented on templates/monthly-update.md
> -
I think it's good to leave a comment here so folks have a reminder where to look for this kind of information.

2023-06-05 14:59 UTC, mewzherder approved these changes
lgtm

2023-06-05 17:02 UTC, aryan9600 requested changes

2023-06-05 17:02 UTC, aryan9600 commented on content/en/blog/2023-06-01-may-update/index.md
> +welcome you to our community. It also gives the team a big boost in morale
```suggestion
welcome you to our community, it also gives the team a big boost in morale
```

2023-06-05 17:02 UTC, aryan9600 commented on content/en/blog/2023-06-01-may-update/index.md
> +Demoing Flux, discussing use-cases and discussing what's new. If you
```suggestion
Over the past years, Pinky spoke at conferences, meetups and elsewhere, 
demoing Flux, discussing use-cases and discussing what's new. If you
```

2023-06-05 17:02 UTC, aryan9600 commented on content/en/blog/2023-06-01-may-update/index.md
> +Thanks for all your contributions to Flux! This is well-deserved
```suggestion
Thanks for all your contributions to Flux! This is well-deserved.
```

2023-06-05 17:02 UTC, aryan9600 commented on content/en/blog/2023-06-01-may-update/index.md
> +(https://cert-manager.io/docs/) and [Unfurl](https://cert-manager.io/docs/).
wrong link for Unfurl

2023-06-05 18:09 UTC, somtochiama commented on content/en/blog/2023-06-01-may-update/index.md
> +#### Fixes and improvements
I don't think we need to add everything across all the RC but I will add the support for cosign and helm

2023-06-06 07:09 UTC, dholbach commented on content/en/blog/2023-06-01-may-update/index.md
> +Flux, it is recommended to upgrade Kubernetes to 1.27.1 or newer. The upgarde to
```suggestion
Flux, it is recommended to upgrade Kubernetes to 1.27.1 or newer. The upgrade to
```

2023-06-06 07:15 UTC, dholbach commented on content/en/blog/2023-06-01-may-update/index.md
> +{{< gallery match="images/*" sortOrder="desc" rowHeight="150" margins="5"
Maybe increase the size of the photos  somewhat?

2023-06-06 07:34 UTC, makkes reviewed
Overall great post. Thanks @somtochiama. Just a couple of nits really.

2023-06-06 07:34 UTC, makkes commented on content/en/blog/2023-06-01-may-update/index.md
> +On our path to GA, we released v2.0.0-rc5, the fifth release candidate for
```suggestion
On our path to GA, we released [v2.0.0-rc5](https://github.com/fluxcd/flux2/releases/tag/v2.0.0-rc.5), the fifth release candidate for
```

2023-06-06 07:34 UTC, makkes commented on content/en/blog/2023-06-01-may-update/index.md
> +            previewType="blur" embedPreview=true lastRow="nojustify" >}}
The rendered order of logos in here doesn't match the list below but I don't know how to fix that. If we can't find a way to change it, let's change the order of the list below to match the logos here.

2023-06-06 07:34 UTC, makkes commented on content/en/blog/2023-06-01-may-update/index.md
> +### Flux members, contributors, and maintainers!
Love the shoutouts here!!

2023-06-06 14:48 UTC, makkes approved these changes

2023-06-06 17:29 UTC, hiddeco commented on content/en/blog/2023-06-01-may-update/index.md
> +date: 2023-05-10 7:30:00+00:00
This should be today, I think?

2023-06-06 19:25 UTC, hiddeco approved these changes

2023-06-06 19:26 UTC, merged