Landing Page Adopters Carousel [Draft]
fluxcd/website pull request #397
Opened 2021-07-07 17:31 UTC by juozasg

Static draft preview of the adopters layout on the landing page. Carousel controls (Next/Previous buttons and Current Item Indicator) commented out to make it very simple and clean. Clicking the item links to the /adopters Page. 

What remains to be done:
* Clean up and factor out the markup
* Integrate with a YAML data source
* Modify/clone existing python scripts to generate YAML data weekly.  
* Update this to work with Landing Page section header color fixes that need to happen first

One idea: instead of generating 5 items weekly we could include all the items with logos and shuffle them randomly. 

@dholbach @hiddeco

2021-07-08 06:20 UTC, dholbach requested changes
If you change to relative urls for images they should show up.

2021-07-08 06:20 UTC, dholbach commented on content/en/_index.html
> +            <img class="d-block w-100" src="https://fluxcd.io/img/logos/sageailabs.png" alt="First slide">
```suggestion
            <img class="d-block w-100" src="/img/logos/sageailabs.png" alt="First slide">
```

2021-07-08 06:20 UTC, dholbach commented on content/en/_index.html
> +            <img class="d-block w-100" src="http://localhost:1313/img/logos/bimspot.png" alt="Second slide">
```suggestion
            <img class="d-block w-100" src="/img/logos/bimspot.png" alt="Second slide">
```

2021-07-08 06:20 UTC, dholbach commented on content/en/_index.html
> +            <img class="d-block w-100" src="http://localhost:1313/img/logos/blackmirror-media.png" alt="Third slide">
```suggestion
            <img class="d-block w-100" src="/img/logos/blackmirror-media.png" alt="Third slide">
```

2021-07-08 06:20 UTC, dholbach commented on content/en/_index.html
> +            <img class="d-block w-100" src="https://fluxcd.io/img/logos/d2iq.png" alt="Third slide">
```suggestion
            <img class="d-block w-100" src="/img/logos/d2iq.png" alt="Third slide">
```

2021-07-08 06:20 UTC, dholbach commented on content/en/_index.html
> +            <img class="d-block w-100" src="http://localhost:1313/img/logos/adoreme.png" alt="Third slide">
```suggestion
            <img class="d-block w-100" src="/img/logos/adoreme.png" alt="Third slide">
```

2021-07-08 07:50 UTC, dholbach commented
Nice, now it's working! Do we want to subtitle the logos with the company name maybe?

2021-07-09 08:05 UTC, juozasg commented
Possibly. If the logo already contains the name it could look redundant. I think the source YAML should contain the label (or no label). I will experiment with that and will update the PR.

2021-07-12 08:18 UTC, dholbach commented
Looks like it's back to absolute urls for the logos including `localhost:1313`?

2021-07-13 11:17 UTC, dholbach commented
One piece of feedback I got was:
> Looks good on my mobile, dominates the screen a bit on a laptop

2021-07-13 11:18 UTC, dholbach commented
I'll look into adding a solution for showing company names as caption if necessary.

2021-07-13 14:25 UTC, dholbach commented on layouts/shortcodes/blocks/carousel.html
> -          {{ readFile "/content/en/adopters_carousel_include.html" | safeHTML }}
Not sure why this is removed now?

2021-07-14 08:46 UTC, dholbach commented
We just got some feedback that maybe a carousel does not show off the breadth of adopters really well - especially if people are on  the landing page for a short while.

I see two options:

- We could try to see if we can get more logos to show in the carousel at the same time?
- We could move to a more static / non-moving kind of layout?

WDYT?

2021-07-14 09:16 UTC, dholbach commented
@juozasg In the PR above I changed parts of the script to put the logos in groups of 5 - this doesn't look well yet - maybe you can help?

2021-07-14 11:49 UTC, dholbach commented
Another idea: carousel case studies, blogs, endorsements?
- https://www.weave.works/blog/case-study-mettle-leverages-gitops-for-self-service-developer-platform
- https://www.weave.works/blog/case-study-tidepool-streamlines-and-secures-cluster-lifecycle-with-gitops
- https://www.youtube.com/watch?v=59mTx8tBYag
- https://www.youtube.com/watch?v=dEMYVkIU0aU
- https://www.youtube.com/watch?v=ewCnqDgewMg

2021-07-14 13:57 UTC, dholbach commented
A new idea I just had:

have our "wall of logos" in the background (opaque), carousel some of the endorsements over them?

2021-07-14 14:44 UTC, dholbach commented
![Screenshot from 2021-07-14 16-43-08](https://user-images.githubusercontent.com/1346979/125641877-9b6af5f1-d1c1-49d1-a8f0-88490a58b1eb.png)

I worked on something which looks like this right now. The background looks OK-ish. The foreground still needs styling. Happy to get the scripts to generate the right code.

What do people generally feel about this?

2021-07-14 14:45 UTC, dholbach commented
I'd cycle e.g. 5 items over the wall of logos, each being left side image, right side some text or quote.

2021-07-14 21:06 UTC, scottrigby commented
I personally think that would look great! With a clear link to the adopters page so people can see them all, and see how to add themselves?

2021-07-15 15:32 UTC, juozasg commented
Sounds good. I should be able to looks over this tomorrow!

2021-07-16 08:55 UTC, dholbach commented
Please take a look at https://github.com/fluxcd/website/pull/413.

2021-07-28 06:16 UTC, closed without merging